### ISSUE TITLE
Hooks not running

### ISSUE THREAD

**Issue by m-cat** [nflath/save-visited-files#7]
Yo! Looks like this mode immediately opens last-visited files, as soon as it's turned on. This is a problem if someone has this early on in .emacs, since any hooks that are defined later on in their .emacs do not run on auto-opened buffers.

For example, I had a ton of prog-mode hooks defined that didn't seem to have run in my buffers after I restarted Emacs, and it took me a while to realize that the problem was that this mode opened files without running my hooks.

I solved this by turning on your mode after initialization:
```
(use-package save-visited-files
  :init (add-hook 'after-init-hook #'turn-on-save-visited-files-mode))
```

I think this should be the default behavior, or at least recommended in the documentation.

**Comment by nflath** [comment]
I pushed a patch that should test this; mind testing to verify it works?

**Comment by m-cat** [comment]
Code looks good and my tests passed fine. Thanks for fixing this and for the useful package!
